### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lightning02** [CreativeMD/RandomAdditions#18]
crashing on server side going around the world.
http://94.23.242.126/crash-2015-05-28_22.49.14-server.txt

**Comment by CreativeMD** [comment]
Sorry for the delay, did that happens everytime?

**Comment by lightning02** [comment]
it depends, once it happenend going around the End dimension, another going around the normal world.

**Comment by CreativeMD** [comment]
Will be fixed in the next version, which will be release tomorrow or today.
