### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by MCShammer** [CreativeMD/RandomAdditions#2]
When breaking or interacting with a misplaced Windmill that will not render the server crashes. 

I had the mechanic cable tier 1 in place connected to nothing when i placed the windmill, and i beleive i pressed shift as i placed it, causing it to be placed 90 degrees off and into my build. Using version 0.9.4 on a 1.7.10 server.

http://pastebin.com/j3DaUpcg

**Comment by CreativeMD** [comment]
Should be fixed now
