### ISSUE TITLE
Crash, when looking up recipes (NEI)

### ISSUE THREAD

**Issue by avanderthefallen** [CreativeMD/RandomAdditions#20]
---- Minecraft Crash Report ----
// My bad.

Time: 6/28/15 10:10 PM
Description: Rendering item

java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.creativemd.randomadditions.common.item.tools.Tool.getIcon(Tool.java:88)
	at com.creativemd.randomadditions.common.item.ItemTool.getIcon(ItemTool.java:332)
	at com.creativemd.randomadditions.common.item.ItemTool.func_77650_f(ItemTool.java:325)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.creativemd.randomadditions.common.item.tools.Tool.getIcon(Tool.java:88)
	at com.creativemd.randomadditions.common.item.ItemTool.getIcon(ItemTool.java:332)
	at com.creativemd.randomadditions.common.item.ItemTool.func_77650_f(ItemTool.java:325)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)

-- Item being rendered --
Details:
	Item Type: com.creativemd.randomadditions.common.item.ItemTool@2ada7aa0
	Item Aux: 4
	Item NBT: {heat:1b,type:"boots",tourmalinelevel:2}
	Item Foil: true
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)

-- Screen render details --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe
	Mouse location: Scaled: (277, 51). Absolute: (555, 377)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['avander5'/37207, l='MpServer', x=155.65, y=66.50, z=204.13]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (188,64,256), Chunk: (at 12,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 191976 game time, 71690 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityZombie['Zombie'/103428, l='MpServer', x=175.50, y=32.00, z=237.50], EntityZombie['Zombie'/8713, l='MpServer', x=1.93, y=-56.62, z=-24.30], EntityClientPlayerMP['avander5'/37207, l='MpServer', x=155.65, y=66.50, z=204.13], EntityZombie['Zombie'/103690, l='MpServer', x=95.50, y=38.00, z=237.50], EntitySkeleton['Skeleton'/103445, l='MpServer', x=178.44, y=20.00, z=229.94], EntityBat['Bat'/103960, l='MpServer', x=228.78, y=35.67, z=139.75], EntityBat['Bat'/103962, l='MpServer', x=222.22, y=36.00, z=128.50], EntityPig['Pig'/36, l='MpServer', x=89.88, y=64.00, z=129.78], EntityPig['Pig'/37, l='MpServer', x=80.09, y=64.00, z=137.06], EntityBat['Bat'/103462, l='MpServer', x=187.34, y=20.00, z=201.70], EntityPig['Pig'/50, l='MpServer', x=100.22, y=64.00, z=132.91], EntitySheep['Sheep'/51, l='MpServer', x=95.50, y=67.00, z=155.09], EntitySheep['Sheep'/53, l='MpServer', x=94.06, y=68.00, z=161.94], EntitySheep['Sheep'/54, l='MpServer', x=97.03, y=67.00, z=171.97], EntityBat['Bat'/104003, l='MpServer', x=210.10, y=31.48, z=222.25], EntityBat['Bat'/104002, l='MpServer', x=197.97, y=34.29, z=235.66], EntityZombie['Zombie'/104007, l='MpServer', x=234.50, y=46.00, z=227.50], EntityBat['Bat'/104006, l='MpServer', x=215.33, y=35.10, z=206.19], EntitySkeleton['Skeleton'/102985, l='MpServer', x=140.47, y=75.00, z=186.08], EntityBat['Bat'/103241, l='MpServer', x=149.75, y=57.00, z=129.75], EntityCreeper['Creeper'/103501, l='MpServer', x=228.53, y=69.00, z=245.38], EntityHorse['Horse'/78, l='MpServer', x=171.88, y=69.00, z=169.00], EntityHorse['Horse'/79, l='MpServer', x=138.09, y=73.00, z=156.66], EntitySheep['Sheep'/80, l='MpServer', x=142.50, y=69.00, z=259.34], EntitySheep['Sheep'/85, l='MpServer', x=145.22, y=69.00, z=261.31], EntitySheep['Sheep'/87, l='MpServer', x=139.06, y=69.00, z=257.84], EntitySheep['Sheep'/88, l='MpServer', x=158.47, y=64.00, z=262.53], EntityItem['item.item.arrow'/101977, l='MpServer', x=212.34, y=22.13, z=153.78], EntityItem['item.item.bone'/101978, l='MpServer', x=211.91, y=22.13, z=154.63], EntitySheep['Sheep'/110, l='MpServer', x=165.66, y=71.00, z=285.44], EntityCreeper['Creeper'/103537, l='MpServer', x=198.50, y=14.00, z=147.50], EntityCreeper['Creeper'/103538, l='MpServer', x=199.50, y=14.00, z=146.50], EntityPig['Pig'/123, l='MpServer', x=168.97, y=63.00, z=234.09], EntityPig['Pig'/132, l='MpServer', x=206.84, y=63.00, z=166.16], EntityEnderman['Enderman'/103814, l='MpServer', x=194.47, y=33.00, z=252.13], EntitySpider['Spider'/104074, l='MpServer', x=117.72, y=65.00, z=144.94], EntityZombie['Zombie'/104077, l='MpServer', x=212.47, y=20.00, z=167.63], EntityZombie['Zombie'/104076, l='MpServer', x=216.75, y=21.00, z=160.56], EntityBat['Bat'/103567, l='MpServer', x=141.35, y=33.06, z=156.47], EntityBat['Bat'/103054, l='MpServer', x=126.50, y=21.13, z=139.91], EntityBat['Bat'/103310, l='MpServer', x=150.44, y=60.64, z=141.25], EntityZombie['Zombie'/104078, l='MpServer', x=213.63, y=20.00, z=167.63], EntityCreeper['Creeper'/104081, l='MpServer', x=216.03, y=22.00, z=162.56], EntityPig['Pig'/160, l='MpServer', x=203.25, y=63.00, z=169.56], EntityPig['Pig'/161, l='MpServer', x=214.50, y=71.00, z=167.50], EntityBat['Bat'/103330, l='MpServer', x=147.38, y=21.16, z=143.22], EntitySquid['Squid'/101797, l='MpServer', x=154.47, y=56.34, z=232.50], EntitySquid['Squid'/101796, l='MpServer', x=155.66, y=56.36, z=231.76], EntityBat['Bat'/103337, l='MpServer', x=208.22, y=33.82, z=229.69], EntityZombie['Zombie'/103593, l='MpServer', x=121.50, y=64.00, z=142.50], EntityZombie['Zombie'/103596, l='MpServer', x=124.50, y=64.00, z=140.50], EntityCreeper['Creeper'/103601, l='MpServer', x=123.50, y=64.00, z=142.50], EntitySlime['Slime'/54193, l='MpServer', x=179.12, y=33.00, z=244.38], EntityCreeper['Creeper'/103602, l='MpServer', x=127.50, y=64.00, z=142.50], EntitySheep['Sheep'/181, l='MpServer', x=221.91, y=68.00, z=159.13], EntityZombie['Zombie'/104127, l='MpServer', x=210.50, y=40.00, z=147.50], EntityCreeper['Creeper'/103617, l='MpServer', x=98.50, y=64.00, z=133.50], EntityZombie['Zombie'/104129, l='MpServer', x=211.50, y=40.00, z=149.50], EntitySkeleton['Skeleton'/103872, l='MpServer', x=130.50, y=73.00, z=182.50], EntityZombie['Zombie'/104128, l='MpServer', x=210.50, y=40.00, z=148.50], EntitySpider['Spider'/103880, l='MpServer', x=186.50, y=39.00, z=162.50], EntitySlime['Slime'/96974, l='MpServer', x=158.80, y=16.00, z=218.80], EntitySheep['Sheep'/207, l='MpServer', x=232.72, y=69.00, z=244.81], EntitySkeleton['Skeleton'/103891, l='MpServer', x=202.50, y=33.00, z=229.50], EntityBat['Bat'/103637, l='MpServer', x=221.50, y=23.00, z=230.25], EntityCreeper['Creeper'/103892, l='MpServer', x=202.50, y=33.00, z=227.50], EntitySkeleton['Skeleton'/103127, l='MpServer', x=86.50, y=64.00, z=139.50], EntityZombie['Zombie'/103895, l='MpServer', x=222.50, y=39.00, z=159.50], EntityZombie['Zombie'/103894, l='MpServer', x=220.50, y=39.00, z=159.50], EntityZombie['Zombie'/103896, l='MpServer', x=220.50, y=39.00, z=162.50], EntitySpider['Spider'/7643, l='MpServer', x=51.43, y=-17.62, z=3.15], EntitySkeleton['Skeleton'/103130, l='MpServer', x=86.50, y=64.00, z=138.50], EntityZombie['Zombie'/104159, l='MpServer', x=87.50, y=42.00, z=226.50], EntityZombie['Zombie'/104158, l='MpServer', x=93.32, y=42.00, z=227.50], EntityZombie['Zombie'/104160, l='MpServer', x=88.50, y=42.00, z=229.50], EntitySquid['Squid'/103651, l='MpServer', x=91.47, y=59.00, z=217.50], EntitySpider['Spider'/103394, l='MpServer', x=81.50, y=64.00, z=127.50], EntityZombie['Zombie'/103154, l='MpServer', x=115.50, y=13.00, z=267.50], EntityCreeper['Creeper'/103158, l='MpServer', x=182.50, y=17.00, z=134.50], EntityZombie['Zombie'/103931, l='MpServer', x=190.50, y=16.00, z=158.88], EntitySkeleton['Skeleton'/104187, l='MpServer', x=99.50, y=67.00, z=149.50], EntityZombie['Zombie'/103930, l='MpServer', x=194.06, y=17.00, z=164.50], EntityZombie['Zombie'/104186, l='MpServer', x=101.50, y=67.00, z=147.50], EntityZombie['Zombie'/103679, l='MpServer', x=166.34, y=62.00, z=127.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 292086544 bytes (278 MB) / 691535872 bytes (659 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.113.1384 Minecraft Forge 10.13.3.1384 52 mods loaded, 52 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.113.1384} [Forge Mod Loader] (forge-1.7.10-10.13.3.1384-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.3.1384} [Minecraft Forge] (forge-1.7.10-10.13.3.1384-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.6.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	creativecore{1.0} [CreativeCore] (CreativeCore v1.1.4 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ESM{10.0.112} [Epic Siege Mod] (EpicSiegeMod-10.0.112.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.dimensionalSlice{0.8.94} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization{0.8.94} [Factorization] (Factorization-1.7.10-0.8.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.misc{0.8.94} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	randomadditions{0.11} [RandomAdditions] (RandomAdditions Pre-Alpha 0.11.8 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	runicdungeons{1.1.4} [Runic Dungeons] (runicdungeons-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore: -[1.7.10]3.0.2-262
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce 820M/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by avanderthefallen** [comment]
+ This happens with every "Heated" "Gem" product, implemented by the mod.

**Comment by CreativeMD** [comment]
Don't have any errors :O can't reproduce that

**Comment by CreativeMD** [comment]
Fixed it in the newest version
