### ISSUE TITLE
[Feature Request] Mekanism support

### ISSUE THREAD

**Issue by Protheus** [CreativeMD/RandomAdditions#21]
Provide mekanism crusher support. for the rest this mode is beautifull ! :-) :+1:

**Comment by Protheus** [comment]
Additional Ore support for the crusher:
- Yellorite (Big Reactor)
- Ferrous Ore (nickel)  (TE)

**Comment by CreativeMD** [comment]
I already added Ferrous Ore.
I will add a support for InGameConfigManager today, you will be able to add these ore.

If you want me to add it to RandomAdditions you will have to give me the name of the ores.

**Comment by Protheus** [comment]
Osmium ore (mekanism)
Yellorite (Big Reactor)

**Comment by CreativeMD** [comment]
Added in v0.11.15
