### ISSUE TITLE
[Feature] Auto eject support

### ISSUE THREAD

**Issue by Protheus** [CreativeMD/RandomAdditions#25]
Auto eject from a mechanic crusher in to the mechanic furnace or any other block (like ender io, mekanism).

Now you need pipes to get them from the crusher in to a furnace. Would be nice if they can do it automatically.

**Comment by CreativeMD** [comment]
Sorry, but it would be a bigger feature, because it would need to be configurable. I'm planning to port all of my mods to 1.9 as soon as possible and i will redesign RandomAdditions, but until than i need to put some effort into LittleTiles and HandCraft.

**Comment by Protheus** [comment]
That is oke ... It is a feature request
