### ISSUE TITLE
crash happen

### ISSUE THREAD

**Issue by ISJump** [CreativeMD/RandomAdditions#29]
with ver 24
[crash-2016-07-10_01.00.31-client.txt](https://github.com/CreativeMD/RandomAdditions/files/355645/crash-2016-07-10_01.00.31-client.txt)

with ver 13
[crash-2016-07-10_01.02.41-client.txt](https://github.com/CreativeMD/RandomAdditions/files/355646/crash-2016-07-10_01.02.41-client.txt)

**Comment by CreativeMD** [comment]
Sorry, but i have no idea why this is happening. Maybe try to only run RandomAdditions and CreativeCore?

**Comment by ISJump** [comment]
solution 

redownload the minecraft forge and liteloder

**Comment by CreativeMD** [comment]
nice :D

**Comment by ISJump** [comment]
and fine new bug while shooting bow it shooting render is error

like all the random additions bow  shooting the arrow hurt me and using cousutmnpc it you can look how it go away  

humm im not good at eng but i can say that the arrow rotate on it`s way

**Comment by CreativeMD** [comment]
Yeah, i'm sorry. There are a lot of issue, but this mod is abandoned and won't be updated to the newer version. I'm not really supporting it anymore.

**Comment by ISJump** [comment]
oh i see
