### ISSUE TITLE
Mods Incompatibles/Incompatible Mods

### ISSUE THREAD

**Issue by TheGaboGGamer** [CreativeMD/RandomAdditions#5]
Muestro Este Problema Porque He Visto Y He Probado Que Hay Ciertos Mods Que No Son Compatibles Con El RandomAdditions/Sampling This Issue Because I Have Seen And I Tried That There Is Certain Mods Are Not Compatible With RandomAdditions

**Comment by CreativeMD** [comment]
Sorry, it is hard to understand what you are saying. Could you send me at least the crash report?
