### ISSUE TITLE
Ores are registered with the wrong Ore Dictionary names

### ISSUE THREAD

**Issue by EXTER7** [CreativeMD/RandomAdditions#6]
Using version 0.10.2
Copper, Tin, and Ruby ores are registered with the wrong Ore Dictionary names.

Ruby ore is registered as "oreCopper".
Copper ore is registered as "oreTin".
Tin ore is registered as "oreRuby".

This causes machines from other mods to output the wrong material when using RandomAdiitions ores.

Screenshots of the issue using the Metallurgy crusher as an example:
![screenshot](https://cloud.githubusercontent.com/assets/3077881/5771761/ecf2367e-9d1a-11e4-9e5c-6c598fb8ce6e.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/3077881/5771762/ecf26892-9d1a-11e4-8fcc-11d5e407e9c3.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/3077881/5771763/ecf73070-9d1a-11e4-99f6-864b31958f77.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/3077881/5771764/ecf9eab8-9d1a-11e4-9619-0c15fbf795e6.png)

**Comment by CreativeMD** [comment]
Oh, are you using my newest prerelease?

**Comment by EXTER7** [comment]
updating to version 0.10.4 fixed this issue.
