### ISSUE TITLE
InvocationTargetException Error Spamming Console

### ISSUE THREAD

**Issue by jermangarc** [CreativeMD/RandomAdditions#7]
http://pastebin.com/EtE1Tvwc
 All of the RA block textures are not showing up in creative tab and in NEI. When I filter to search only RA blocks, the fps drops dramatically.

Looks like it's having some issue with bdew's library?

**Comment by CreativeMD** [comment]
Yes what is bdew's library?

**Comment by jermangarc** [comment]
It's http://bdew.net/. Actually, he has a hotfix available. I'm trying it out. Not sure it will fix this issue though. I'll keep you posted.

**Comment by jermangarc** [comment]
I installed bdew's update as well as RA Pre-Alpha 0.11.1, still getting the console messages.
Here are the latest console messages that keep spamming.
http://pastebin.com/hJ6pCVgd

**Comment by bdew** [comment]
> modelID = config.get("Client", "RenderingModelID", 574).getInt(574);

You should use  RenderingRegistry.getNextAvailableRenderId() to allocate a render id at startup. Otherwise you get collisions like that.

**Comment by CreativeMD** [comment]
Will be fixed in the next pre release.

**Comment by jermangarc** [comment]
Thanks guys!
